import { StaffRole, type StaffMember } from "./types";

export const MOCK_STAFF: StaffMember[] = [
  { id: 1, name: "Иван Иванов", email: "ivan.ivanov@company.com", role: StaffRole.EngineeringManager, department: "Engineering" },
  { id: 2, name: "Пётр Петров", email: "petr.petrov@company.com", role: StaffRole.FrontendDeveloper, department: "Engineering" },
  { id: 3, name: "Анна Сидорова", email: "anna.sidorova@company.com", role: StaffRole.ProductDesigner, department: "Design" },
  { id: 4, name: "Мария Кузнецова", email: "maria.kuznetsova@company.com", role: StaffRole.ProductManager, department: "Product" },
  { id: 5, name: "Алексей Смирнов", email: "alexey.smirnov@company.com", role: StaffRole.HRBusinessPartner, department: "People Operations" },
  { id: 6, name: "Дмитрий Попов", email: "dmitry.popov@company.com", role: StaffRole.BackendDeveloper, department: "Engineering" },
  { id: 7, name: "Елена Васильева", email: "elena.vasilieva@company.com", role: StaffRole.UXUIDesigner, department: "Design" },
  { id: 8, name: "Михаил Соколов", email: "mikhail.sokolov@company.com", role: StaffRole.DevOpsEngineer, department: "Infrastructure" },
  { id: 9, name: "Ольга Михайлова", email: "olga.mikhailova@company.com", role: StaffRole.ProjectManager, department: "Operations" },
  { id: 10, name: "Фёдор Фёдоров", email: "fedor.fedorov@company.com", role: StaffRole.QAEngineer, department: "Quality Assurance" },
  { id: 11, name: "Татьяна Николаева", email: "tatiana.nikolaeva@company.com", role: StaffRole.Recruiter, department: "Talent Acquisition" },
  { id: 12, name: "Игорь Морозов", email: "igor.morozov@company.com", role: StaffRole.FullstackDeveloper, department: "Engineering" },
  { id: 13, name: "Наталья Волкова", email: "natalia.volkova@company.com", role: StaffRole.DataAnalyst, department: "Analytics" },
  { id: 14, name: "Андрей Лебедев", email: "andrey.lebedev@company.com", role: StaffRole.SystemAdministrator, department: "IT Operations" },
  { id: 15, name: "Сергей Козлов", email: "sergey.kozlov@company.com", role: StaffRole.SalesManager, department: "Sales" },
  { id: 16, name: "Юлия Новикова", email: "yulia.novikova@company.com", role: StaffRole.MarketingManager, department: "Marketing" },
  { id: 17, name: "Владимир Морозов", email: "vladimir.morozov@company.com", role: StaffRole.SecurityEngineer, department: "Security" },
  { id: 18, name: "Екатерина Петрова", email: "ekaterina.petrova@company.com", role: StaffRole.FinanceAnalyst, department: "Finance" },
  { id: 19, name: "Антон Павлов", email: "anton.pavlov@company.com", role: StaffRole.LegalCounsel, department: "Legal" },
  { id: 20, name: "Евгения Степанова", email: "evgenia.stepanova@company.com", role: StaffRole.CustomerSupportSpecialist, department: "Customer Support" },
  { id: 21, name: "Николай Орлов", email: "nikolay.orlov@company.com", role: StaffRole.FrontendDeveloper, department: "Engineering" },
  { id: 22, name: "София Макарова", email: "sofia.makarova@company.com", role: StaffRole.ProductManager, department: "Product" },
  { id: 23, name: "Денис Зайцев", email: "denis.zaitsev@company.com", role: StaffRole.BackendDeveloper, department: "Engineering" },
  { id: 24, name: "Кристина Борисова", email: "kristina.borisova@company.com", role: StaffRole.ProductDesigner, department: "Design" },
  { id: 25, name: "Валерий Романов", email: "valery.romanov@company.com", role: StaffRole.HRBusinessPartner, department: "People Operations" },
  { id: 26, name: "Алина Киселева", email: "alina.kiseleva@company.com", role: StaffRole.FullstackDeveloper, department: "Engineering" },
  { id: 27, name: "Артем Сергеев", email: "artem.sergeev@company.com", role: StaffRole.ProjectManager, department: "Operations" },
  { id: 28, name: "Вероника Полякова", email: "veronika.polyakova@company.com", role: StaffRole.QAEngineer, department: "Quality Assurance" },
  { id: 29, name: "Илья Савельев", email: "ilya.savelev@company.com", role: StaffRole.UXUIDesigner, department: "Design" },
  { id: 30, name: "Дарья Тихонова", email: "daria.tikhonova@company.com", role: StaffRole.DataAnalyst, department: "Analytics" },
  { id: 31, name: "Максим Егоров", email: "maxim.egorov@company.com", role: StaffRole.DevOpsEngineer, department: "Infrastructure" },
  { id: 32, name: "Полина Белова", email: "polina.belova@company.com", role: StaffRole.Recruiter, department: "Talent Acquisition" },
  { id: 33, name: "Григорий Андреев", email: "grigory.andreev@company.com", role: StaffRole.EngineeringManager, department: "Engineering" },
  { id: 34, name: "Виктория Захарова", email: "victoria.zakharova@company.com", role: StaffRole.MarketingManager, department: "Marketing" },
  { id: 35, name: "Руслан Комаров", email: "ruslan.komarov@company.com", role: StaffRole.SalesManager, department: "Sales" },
  { id: 36, name: "Лариса Фомина", email: "larisa.fomina@company.com", role: StaffRole.CustomerSupportSpecialist, department: "Customer Support" },
  { id: 37, name: "Павел Громов", email: "pavel.gromov@company.com", role: StaffRole.SystemAdministrator, department: "IT Operations" },
  { id: 38, name: "Нина Григорьева", email: "nina.grigorieva@company.com", role: StaffRole.FinanceAnalyst, department: "Finance" },
  { id: 39, name: "Роман Крылов", email: "roman.krylov@company.com", role: StaffRole.SecurityEngineer, department: "Security" },
  { id: 40, name: "Лидия Соловьева", email: "lidia.solovieva@company.com", role: StaffRole.LegalCounsel, department: "Legal" },
  { id: 41, name: "Кирилл Филатов", email: "kirill.filatov@company.com", role: StaffRole.FrontendDeveloper, department: "Engineering" },
  { id: 42, name: "Анастасия Ершова", email: "anastasia.ershova@company.com", role: StaffRole.ProductManager, department: "Product" },
  { id: 43, name: "Олег Воробьев", email: "oleg.vorobev@company.com", role: StaffRole.BackendDeveloper, department: "Engineering" },
  { id: 44, name: "Марина Орлова", email: "marina.orlova@company.com", role: StaffRole.ProductDesigner, department: "Design" },
  { id: 45, name: "Георгий Медведев", email: "georgy.medvedev@company.com", role: StaffRole.QAEngineer, department: "Quality Assurance" },
  { id: 46, name: "Ксения Рябова", email: "ksenia.ryabova@company.com", role: StaffRole.HRBusinessPartner, department: "People Operations" },
  { id: 47, name: "Станислав Беляев", email: "stanislav.belyaev@company.com", role: StaffRole.FullstackDeveloper, department: "Engineering" },
  { id: 48, name: "Милана Тарасова", email: "milana.tarasova@company.com", role: StaffRole.DataAnalyst, department: "Analytics" },
  { id: 49, name: "Вадим Ковалев", email: "vadim.kovalev@company.com", role: StaffRole.DevOpsEngineer, department: "Infrastructure" },
  { id: 50, name: "Надежда Гордеева", email: "nadezhda.gordeeva@company.com", role: StaffRole.ProjectManager, department: "Operations" },
  { id: 51, name: "Егор Кудрявцев", email: "egor.kudryavtsev@company.com", role: StaffRole.SalesManager, department: "Sales" },
  { id: 52, name: "Валентина Титова", email: "valentina.titova@company.com", role: StaffRole.MarketingManager, department: "Marketing" },
  { id: 53, name: "Степан Фролов", email: "stepan.frolov@company.com", role: StaffRole.SystemAdministrator, department: "IT Operations" },
  { id: 54, name: "Александра Мельникова", email: "alexandra.melnikova@company.com", role: StaffRole.CustomerSupportSpecialist, department: "Customer Support" },
  { id: 55, name: "Ярослав Алексеев", email: "yaroslav.alekseev@company.com", role: StaffRole.SecurityEngineer, department: "Security" },
  { id: 56, name: "Инна Дмитриева", email: "inna.dmitrieva@company.com", role: StaffRole.Recruiter, department: "Talent Acquisition" },
  { id: 57, name: "Вячеслав Матвеев", email: "vyacheslav.matveev@company.com", role: StaffRole.EngineeringManager, department: "Engineering" },
  { id: 58, name: "Раиса Федотова", email: "raisa.fedotova@company.com", role: StaffRole.FinanceAnalyst, department: "Finance" },
  { id: 59, name: "Константин Чернов", email: "konstantin.chernov@company.com", role: StaffRole.LegalCounsel, department: "Legal" },
  { id: 60, name: "Светлана Абрамова", email: "svetlana.abramova@company.com", role: StaffRole.UXUIDesigner, department: "Design" },
  { id: 61, name: "Арсений Семенов", email: "arseny.semenov@company.com", role: StaffRole.BackendDeveloper, department: "Engineering" },
  { id: 62, name: "Любовь Куликова", email: "lyubov.kulikova@company.com", role: StaffRole.ProductManager, department: "Product" },
  { id: 63, name: "Борис Миронов", email: "boris.mironov@company.com", role: StaffRole.FrontendDeveloper, department: "Engineering" },
  { id: 64, name: "Жанна Капустина", email: "zhanna.kapustina@company.com", role: StaffRole.ProductDesigner, department: "Design" },
  { id: 65, name: "Лев Никитин", email: "lev.nikitin@company.com", role: StaffRole.FullstackDeveloper, department: "Engineering" },
  { id: 66, name: "Алёна Селезнева", email: "alena.selezneva@company.com", role: StaffRole.QAEngineer, department: "Quality Assurance" },
  { id: 67, name: "Тимур Данилов", email: "timur.danilov@company.com", role: StaffRole.DevOpsEngineer, department: "Infrastructure" },
  { id: 68, name: "Зоя Карпова", email: "zoya.karpova@company.com", role: StaffRole.DataAnalyst, department: "Analytics" },
  { id: 69, name: "Евгений Власов", email: "evgeny.vlasov@company.com", role: StaffRole.ProjectManager, department: "Operations" },
  { id: 70, name: "Оксана Маслова", email: "oksana.maslova@company.com", role: StaffRole.HRBusinessPartner, department: "People Operations" },
  { id: 71, name: "Даниил Блинов", email: "daniil.blinov@company.com", role: StaffRole.SalesManager, department: "Sales" },
  { id: 72, name: "Ангелина Ермакова", email: "angelina.ermakova@company.com", role: StaffRole.MarketingManager, department: "Marketing" },
  { id: 73, name: "Матвей Голубев", email: "matvey.golubev@company.com", role: StaffRole.SystemAdministrator, department: "IT Operations" },
  { id: 74, name: "Кира Сазонова", email: "kira.sazonova@company.com", role: StaffRole.CustomerSupportSpecialist, department: "Customer Support" },
  { id: 75, name: "Филипп Шаров", email: "filipp.sharov@company.com", role: StaffRole.SecurityEngineer, department: "Security" },
  { id: 76, name: "Тамара Панова", email: "tamara.panova@company.com", role: StaffRole.Recruiter, department: "Talent Acquisition" },
  { id: 77, name: "Юрий Осипов", email: "yury.osipov@company.com", role: StaffRole.FinanceAnalyst, department: "Finance" },
  { id: 78, name: "Диана Лазарева", email: "diana.lazareva@company.com", role: StaffRole.LegalCounsel, department: "Legal" },
  { id: 79, name: "Семен Котов", email: "semen.kotov@company.com", role: StaffRole.CustomerSupportSpecialist, department: "Customer Support" },
  { id: 80, name: "Вера Калинина", email: "vera.kalinina@company.com", role: StaffRole.MarketingManager, department: "Marketing" },
];
